### ISSUE TITLE
Foundation Game Design

### ISSUE THREAD

**Issue by lawalm** [kittykatattack/agdt#1]
I don't seem to find a place where I could raise an issue apart from here so my apologise if this is not
the right place. The Time Bomb Panic game timer starts immediately the browser opens.  It would be better if the player could press play to start the timer. Also I notice that in all of your examples do you don't have an instance of a screen menu, start button , not even one. Since I am a learner I would like help adding a title screen or main menu to the game template .. 

Regards Marlene

**Comment by kittykatattack** [comment]
Hi Marlene,

"Foundation Game Design with HTML5" is a very basic beginner's book about learning the fundamentals of programming and we does not go into the specifics of UI design.
Creating a start button and intro screen is left as an exercise for the reader.
"Advanced Game Design with HTML5" and "Learn PixiJS" do, however cover these more advanced topics.
